### ISSUE TITLE
if the slice size is not large enough to contain the slice text size, the text will not be shown

### ISSUE THREAD

**Issue by flypigz** [xyfeng/XYPieChart#13]
see below, if the slice size is not large enough to contain the slice text size, it will not be displayed....

I try to comment the  codes below and allow to display text, but it seems that the text is covered by its sibling slices...... faint, is there any way to fix this?

Can we put the text layer above all the slice layers ???? so it won't be covered. thansk.
- (void)setShowPercentage:(BOOL)showPercentage
  {
  _showPercentage = showPercentage;
  for(SliceLayer _layer in _pieView.layer.sublayers)
  {
      CATextLayer *textLayer = [[layer sublayers] objectAtIndex:0];
      [textLayer setHidden:!_showLabel];
      if(!_showLabel) return;
      NSString *label;
      if(_showPercentage)
          label = [NSString stringWithFormat:@"%0.0f%%", layer.percentage_100];
      else
          label = (layer.text)?layer.text:[NSString stringWithFormat:@"%0.0f", layer.value];
      CGSize size = [label sizeWithFont:self.labelFont];
  
  ```
  if(M_PI*2*_labelRadius*layer.percentage < MAX(size.width,size.height))
  {
      [textLayer setString:@""];
  }
  else
  {
      [textLayer setString:label];
      [textLayer setBounds:CGRectMake(0, 0, size.width, size.height)];
  }
  ```
  
  }
  }

**Comment by xyfeng** [comment]
For animation purpose, there is nothing wrong with this code architecture, if you want that specific feature, feel free to write your own lib.

**Comment by flypigz** [comment]
The  BTSPieChart use a separate layer architecture，the slice and text lies in different layers. I think this what I want, but the author does not maintain this project for a long time....

May be the XYPieChart architecture is simple and better for animation, but if the slice is too small to place the text, and XYPieChart simply replace the text with @"" (or the text will be cropped), it is a little strange.

Anyway, thanks for your response.
