### ISSUE TITLE
Selecting a label to select a slice.

### ISSUE THREAD

**Issue by randykittinger** [xyfeng/XYPieChart#14]
I positioned the labels to appear outside the pie slices. Now I would like to be able to also select the text in order to select a pie slice.
I tried getting coordinates of each text label but strangely each label has the same cgpoints.

**Comment by xyfeng** [comment]
first of all, this is not the issue. 
second, text label is a sublayer of the slice, so the relative position are the same.
To your question, did you try to loop the text layers to see whether the touch point are inside the layer? That may solve your problem.

**Comment by randykittinger** [comment]
That worked, thx a lot :) 

Am 17.10.2012 um 16:16 schrieb XY Feng notifications@github.com:
