### ISSUE TITLE
PieChart appears very tiny when it used with storyboard

### ISSUE THREAD

**Issue by mlibary** [xyfeng/XYPieChart#18]
PieChart appears very tiny when it used with storyboard !!!

**Comment by d2burke** [comment]
You can adjust the size of the view you use to display it, as well as the chart Radius.  I do not believe this has anything to do with the Storyboard.

**Comment by mlibary** [comment]
Thank you d2burke .. you are right it can be adjusted

[self.pieChartRight setLabelRadius:100];

**Comment by d2burke** [comment]
you're quite welcome :)
