### ISSUE TITLE
[Feature] Add labelForSliceAtIndex method to XYPieChartDataSource

### ISSUE THREAD

**Issue by ItamarM** [xyfeng/XYPieChart#3]
Hey!

I played with your component and i have to say nice work so far.
The only thing that miss in this component is the ability to add texts on each slice.

Cheers,
 I.

**Comment by xyfeng** [comment]
Hi Itamar,
  Thank you for your feedback.
  The slice value are UILabels, you can modify that.
  You can also get the slice position very easy.
  Do you have a design in mind for that method?

best,
xy

On Wed, May 16, 2012 at 9:15 AM, ItamarM <
reply@reply.github.com

**Comment by ItamarM** [comment]
Hi XY,
  Basically every time you build the % of each slice you need to ask the delegate if it has string for it & concat it to the % label string.

cheers,
I.
