### ISSUE TITLE
pieChart:textForSliceAtIndex is not called

### ISSUE THREAD

**Issue by trivektor** [xyfeng/XYPieChart#37]
Hi,

I'm having an issue where pieChart:textForSliceAtIndex is not called. In my code, I created the pie chart programmatically and assigned delegate and dataSource but the method was not called. 'valueForSliceAtIndex' and 'colorForSliceAtIndex' were called though.

Here's my code (I'm using RubyMotion btw)

```
view = UIView.alloc.initWithFrame(self.view.bounds)
view.backgroundColor = UIColor.whiteColor
view.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight

@pieChart = XYPieChart.alloc.initWithFrame([[340, 100], [400, 400]])
@pieChart.pieRadius = 200
@pieChart.delegate = self
@pieChart.dataSource = self
view.addSubview(@pieChart)
```

self.view.addSubview(view)

Thanks.

**Comment by kmonaghan** [comment]
showPercentage is set to YES by default so you need to explicitly set it to NO if you want the labels to appear:

```
@pieChart.showPercentage = NO;
```
