### ISSUE TITLE
Add '%' to the percentage label if required

### ISSUE THREAD

**Issue by ItamarM** [xyfeng/XYPieChart#4]
at [updateLabelForLayer:(SliceLayer _)pieLayer value:(CGFloat)value]
if "_showPercentage==TRUE" you can show the percentage symbol, hence change
label = [NSString stringWithFormat:@"%0.0f", pieLayer.percentage_100];
to
label = [NSString stringWithFormat:@"%%%0.0f", pieLayer.percentage*100];

cheers,
I.

**Comment by xyfeng** [comment]
now you can use the new delegate method to create custom text label for each slice, please check the new update
