### ISSUE TITLE
Applying transform to SliceLayers does not working.

### ISSUE THREAD

**Issue by manuyavuz** [xyfeng/XYPieChart#53]
I wanted to customise display style for selected slices in a chart.

I applied scale transform, but it's not working as expected by default.

What I see is that bounds of SliceLayers are CGRectZero, so setting anchor point on layer does not help.

I've managed to get the animation that I want by setting bounds and position values of SliceLayer objects accordingly, then applying scale transform. 

I think it would be appropriate to set bounds for SliceLayer s in reloadData method. What do you think? If it's ok, I could implement and send a pull request..

Besides that,  I propose to implement an interface which enables users to customise selected/deselected slice animation behaviours. Currently, you are applying a translation to position property of layers. However, it could be any generic CATransform3D struct, therefore the library will have a much more flexible interface. 

Maybe we can define two public CATransform3D properties like this:

@property (nonatomic, assign) CATransform3D selectedSliceTransform;
@property (nonatomic, assign) CATransform3D deselectedSliceTransform;

I'm open to suggestions..

By the way, thanks for the great library!

**Comment by stlwtr** [comment]
i like it
